# Show the dongle's own battery level along with the keyboard halves
CONFIG_ZMK_DONGLE_DISPLAY_DONGLE_BATTERY=y

# Show MacOS modifier symbols (Command/Option) instead of Windows (Win/Alt)
CONFIG_ZMK_DONGLE_DISPLAY_MAC_MODIFIERS=y

# Enable the Words-Per-Minute (WPM) meter
CONFIG_ZMK_DONGLE_DISPLAY_WPM=y
